services:
  mysql-db:
    image: mysql:8.0
    container_name: outlet-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: your_password
      MYSQL_DATABASE: OutletRentalDb
    ports:
      - "3306:3306"

  mongo-db:
    image: mongo:latest
    container_name: outlet-mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password